version: '3'


includes:

  nixos:
      taskfile: ./nixos/taskfile.yml
      dir: ./nixos

  home:
      taskfile: ./home/taskfile.yml
      dir: ./home

  ags:
      taskfile: ./ags/taskfile.yml
      dir: ./ags


tasks:

  show:
    desc: Show configuration and generations.
    cmds:
      - nix flake show
      - task: nixos:show

  check:
    desc: Validate configuration.
    cmds:
      - nix flake check --impure

  diff:
    desc: Build system configuration, do not activate but show changes.
    cmds:
      - task: nixos:diff
