version: '3'


includes:

  system:
      taskfile: ./system/taskfile.yml
      dir: ./nixosystems

  home:
      taskfile: ./home/taskfile.yml
      dir: ./home


tasks:

  show:
    desc: Show configuration and generations.
    cmds:
      - nix flake metadata
      - nix flake show
      - task: system:show

  check:
    desc: Validate configuration.
    cmds:
      - nix flake check --impure

  diff:
    desc: Build system configuration, do not activate but show changes.
    cmds:
      - task: system:diff

  update:
    desc: Updates the lock file.
    cmds:
      - nix flake update
