version: '3'


tasks:

  switch:
    desc: "Build configuration, make it default, and switch."
    cmds:
      - home-manager switch --flake '..'
      #- home-manager switch --flake ..#mox-air-m4-mox
