{
  pkgs,
  ...
}:
{
  fonts.packages = with pkgs;
  [
    dina-font
    fira-code
    fira-code-symbols
    font-awesome
    inriafonts
    liberation_ttf
    libertinus
    mplus-outline-fonts.githubRelease
    #nerd-fonts.fira-code
    nerd-fonts.ubuntu
    nerd-fonts.ubuntu-mono
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-color-emoji
    proggyfonts
    ubuntu-sans
  ];
}
